name: 🏗️ Build
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: jcdcdev/jcdcdev.Umbraco.Github.Build@main
        with:
          project-name: Umbraco.Community.SimpleContentApps
          project-path: src/Umbraco.Community.SimpleContentApps/Umbraco.Community.SimpleContentApps.csproj
          umbraco-version: 10